alter table public.orders
  add column if not exists idempotency_key text,
  add column if not exists inventory_reserved_at timestamptz,
  add column if not exists inventory_released_at timestamptz,
  add column if not exists checkout_expires_at timestamptz;

create unique index if not exists orders_idempotency_key_idx
  on public.orders(idempotency_key)
  where idempotency_key is not null;

create table if not exists public.checkout_attempts (
  id bigint generated by default as identity primary key,
  fingerprint_hash text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create index if not exists checkout_attempts_fingerprint_created_idx
  on public.checkout_attempts(fingerprint_hash, created_at desc);
create index if not exists checkout_attempts_phone_created_idx
  on public.checkout_attempts(phone, created_at desc);

create table if not exists public.mpesa_callback_events (
  checkout_request_id text primary key,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  subscribed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_requests (
  id uuid primary key default gen_random_uuid(),
  request_number text not null unique,
  full_name text not null,
  email text not null,
  phone text,
  category text not null,
  order_reference text,
  message text not null,
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_newsletter_subscribers_updated_at on public.newsletter_subscribers;
create trigger set_newsletter_subscribers_updated_at
before update on public.newsletter_subscribers
for each row execute function public.set_updated_at();

drop trigger if exists set_support_requests_updated_at on public.support_requests;
create trigger set_support_requests_updated_at
before update on public.support_requests
for each row execute function public.set_updated_at();

alter table public.checkout_attempts enable row level security;
alter table public.mpesa_callback_events enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.support_requests enable row level security;

create or replace function public.release_checkout_inventory(p_order_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders%rowtype;
begin
  select * into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found
    or v_order.inventory_reserved_at is null
    or v_order.inventory_released_at is not null
    or v_order.payment_status = 'paid' then
    return false;
  end if;

  update public.product_variants as variants
  set stock_quantity = variants.stock_quantity + released.quantity
  from (
    select variant_id, sum(quantity)::integer as quantity
    from public.order_items
    where order_id = p_order_id and variant_id is not null
    group by variant_id
  ) as released
  where variants.id = released.variant_id;

  update public.orders
  set inventory_released_at = now()
  where id = p_order_id;

  return true;
end;
$$;

create or replace function public.create_checkout_order(
  p_order_number text,
  p_idempotency_key text,
  p_fingerprint_hash text,
  p_email text,
  p_full_name text,
  p_phone text,
  p_address text,
  p_delivery_method text,
  p_lines jsonb,
  p_checkout_payload jsonb
)
returns table (
  order_id uuid,
  order_number text,
  total_kes integer,
  checkout_request_id text,
  created boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing record;
  v_customer_id uuid;
  v_order_id uuid;
  v_line jsonb;
  v_variant record;
  v_quantity integer;
  v_subtotal integer := 0;
  v_delivery_fee integer;
begin
  if p_idempotency_key is null or length(p_idempotency_key) < 16 then
    raise exception using errcode = '22023', message = 'INVALID_IDEMPOTENCY_KEY';
  end if;

  select orders.id, orders.order_number, orders.total_kes, payments.mpesa_checkout_request_id
  into v_existing
  from public.orders as orders
  left join public.payments as payments
    on payments.order_id = orders.id and lower(payments.provider) = 'mpesa'
  where orders.idempotency_key = p_idempotency_key
  limit 1;

  if found then
    return query select v_existing.id, v_existing.order_number, v_existing.total_kes,
      v_existing.mpesa_checkout_request_id, false;
    return;
  end if;

  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) < 1 or jsonb_array_length(p_lines) > 20 then
    raise exception using errcode = '22023', message = 'INVALID_CART';
  end if;

  -- Release reservations abandoned beyond the normal STK prompt window.
  perform public.release_checkout_inventory(expired.id)
  from public.orders as expired
  where expired.payment_status = 'pending'
    and expired.checkout_expires_at < now()
    and expired.inventory_reserved_at is not null
    and expired.inventory_released_at is null;

  update public.orders
  set status = 'cancelled', payment_status = 'failed'
  where payment_status = 'pending'
    and checkout_expires_at < now()
    and inventory_released_at is not null;

  update public.payments as payments
  set status = 'failed'
  from public.orders as orders
  where payments.order_id = orders.id
    and orders.payment_status = 'failed'
    and payments.status = 'pending';

  delete from public.checkout_attempts where created_at < now() - interval '1 day';

  -- Serialize rate-limit checks for the same phone and browser fingerprint.
  perform pg_advisory_xact_lock(hashtextextended(p_phone, 0));
  perform pg_advisory_xact_lock(hashtextextended(p_fingerprint_hash, 1));

  if (
    select count(*) from public.checkout_attempts
    where phone = p_phone and created_at > now() - interval '10 minutes'
  ) >= 5 or (
    select count(*) from public.checkout_attempts
    where fingerprint_hash = p_fingerprint_hash and created_at > now() - interval '10 minutes'
  ) >= 10 then
    raise exception using errcode = 'P0001', message = 'CHECKOUT_RATE_LIMITED';
  end if;

  insert into public.checkout_attempts(fingerprint_hash, phone)
  values (p_fingerprint_hash, p_phone);

  insert into public.customers(email, full_name, phone)
  values (p_email, p_full_name, p_phone)
  on conflict (email) do update set email = excluded.email
  returning id into v_customer_id;

  for v_line in select value from jsonb_array_elements(p_lines)
  loop
    v_quantity := (v_line->>'quantity')::integer;
    if v_quantity < 1 or v_quantity > 99 then
      raise exception using errcode = '22023', message = 'INVALID_QUANTITY';
    end if;

    select variants.id, variants.sku, variants.color, variants.price_kes,
      products.name as product_name
    into v_variant
    from public.product_variants as variants
    join public.products as products on products.id = variants.product_id
    where variants.id = (v_line->>'variantId')::uuid
      and variants.is_active
      and products.is_active
    for update of variants;

    if not found then
      raise exception using errcode = 'P0001', message = 'ITEM_UNAVAILABLE';
    end if;

    v_subtotal := v_subtotal + (v_variant.price_kes * v_quantity);
  end loop;

  v_delivery_fee := case when p_delivery_method = 'nairobi-delivery' then 300 else 0 end;

  insert into public.orders(
    order_number, customer_id, status, payment_status, subtotal_kes, delivery_fee_kes,
    total_kes, delivery_county, delivery_town, delivery_address, customer_phone,
    customer_email, idempotency_key, inventory_reserved_at, checkout_expires_at
  ) values (
    p_order_number, v_customer_id, 'pending', 'pending', v_subtotal, v_delivery_fee,
    v_subtotal + v_delivery_fee,
    case when p_delivery_method = 'nairobi-delivery' then 'Nairobi' end,
    case when p_delivery_method = 'town-pickup' then 'Town pickup' end,
    case when p_delivery_method = 'nairobi-delivery' then p_address end,
    p_phone, p_email, p_idempotency_key, now(), now() + interval '15 minutes'
  ) returning id into v_order_id;

  for v_line in select value from jsonb_array_elements(p_lines)
  loop
    v_quantity := (v_line->>'quantity')::integer;

    select variants.id, variants.sku, variants.color, variants.price_kes,
      products.name as product_name
    into v_variant
    from public.product_variants as variants
    join public.products as products on products.id = variants.product_id
    where variants.id = (v_line->>'variantId')::uuid
    for update of variants;

    update public.product_variants
    set stock_quantity = stock_quantity - v_quantity
    where id = v_variant.id and stock_quantity >= v_quantity;

    if not found then
      raise exception using errcode = 'P0001', message = 'INSUFFICIENT_STOCK:' || v_variant.product_name;
    end if;

    insert into public.order_items(
      order_id, variant_id, product_name, sku, color, size, unit_price_kes, quantity, line_total_kes
    ) values (
      v_order_id, v_variant.id, v_variant.product_name, v_variant.sku,
      coalesce(nullif(v_line->>'color', ''), v_variant.color), nullif(v_line->>'size', ''),
      v_variant.price_kes, v_quantity, v_variant.price_kes * v_quantity
    );
  end loop;

  insert into public.payments(
    order_id, provider, provider_reference, amount_kes, status, mpesa_phone_number, raw_payload
  ) values (
    v_order_id, 'mpesa', p_order_number, v_subtotal + v_delivery_fee, 'pending', p_phone,
    jsonb_build_object('checkout', p_checkout_payload)
  );

  return query select v_order_id, p_order_number, v_subtotal + v_delivery_fee, null::text, true;
end;
$$;

create or replace function public.set_mpesa_checkout_request(
  p_order_id uuid,
  p_checkout_request_id text,
  p_merchant_request_id text,
  p_initiation_payload jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.payments
  set provider_reference = p_checkout_request_id,
      mpesa_checkout_request_id = p_checkout_request_id,
      mpesa_merchant_request_id = p_merchant_request_id,
      raw_payload = coalesce(raw_payload, '{}'::jsonb) || jsonb_build_object('initiation', p_initiation_payload)
  where order_id = p_order_id and lower(provider) = 'mpesa' and status = 'pending';
  return found;
end;
$$;

create or replace function public.fail_checkout_order(
  p_order_id uuid,
  p_reason text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.release_checkout_inventory(p_order_id);
  update public.payments
  set status = 'failed', mpesa_result_description = left(p_reason, 500)
  where order_id = p_order_id and lower(provider) = 'mpesa' and status = 'pending';
  update public.orders
  set status = 'cancelled', payment_status = 'failed'
  where id = p_order_id and payment_status <> 'paid';
  return found;
end;
$$;

create or replace function public.finalize_mpesa_payment(
  p_checkout_request_id text,
  p_result_code integer,
  p_result_description text,
  p_amount numeric,
  p_receipt text,
  p_merchant_request_id text,
  p_phone_number text,
  p_transaction_date text,
  p_raw_payload jsonb
)
returns table(recorded boolean, paid boolean, failed boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_payment public.payments%rowtype;
  v_paid boolean;
begin
  select * into v_payment
  from public.payments
  where lower(provider) = 'mpesa' and mpesa_checkout_request_id = p_checkout_request_id
  for update;

  if not found then
    return query select false, false, false;
    return;
  end if;

  if v_payment.status = 'paid' then
    update public.orders set status = 'confirmed', payment_status = 'paid'
    where id = v_payment.order_id;
    return query select true, true, false;
    return;
  end if;

  v_paid := p_result_code = 0
    and p_amount is not null
    and p_amount = v_payment.amount_kes
    and coalesce(p_receipt, '') <> '';

  update public.payments
  set status = case when v_paid then 'paid' else 'failed' end,
      paid_at = case when v_paid then now() else null end,
      mpesa_merchant_request_id = nullif(p_merchant_request_id, ''),
      mpesa_receipt_number = nullif(p_receipt, ''),
      mpesa_result_code = p_result_code,
      mpesa_result_description = nullif(p_result_description, ''),
      mpesa_phone_number = nullif(p_phone_number, ''),
      mpesa_transaction_date = nullif(p_transaction_date, ''),
      raw_payload = coalesce(raw_payload, '{}'::jsonb) || jsonb_build_object('callback', p_raw_payload)
  where id = v_payment.id;

  if v_paid then
    update public.orders set status = 'confirmed', payment_status = 'paid'
    where id = v_payment.order_id;
  else
    perform public.release_checkout_inventory(v_payment.order_id);
    update public.orders set status = 'cancelled', payment_status = 'failed'
    where id = v_payment.order_id;
  end if;

  return query select true, v_paid, not v_paid;
end;
$$;

revoke all on function public.release_checkout_inventory(uuid) from public, anon, authenticated;
revoke all on function public.create_checkout_order(text, text, text, text, text, text, text, text, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.set_mpesa_checkout_request(uuid, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.fail_checkout_order(uuid, text) from public, anon, authenticated;
revoke all on function public.finalize_mpesa_payment(text, integer, text, numeric, text, text, text, text, jsonb) from public, anon, authenticated;

grant execute on function public.release_checkout_inventory(uuid) to service_role;
grant execute on function public.create_checkout_order(text, text, text, text, text, text, text, text, jsonb, jsonb) to service_role;
grant execute on function public.set_mpesa_checkout_request(uuid, text, text, jsonb) to service_role;
grant execute on function public.fail_checkout_order(uuid, text) to service_role;
grant execute on function public.finalize_mpesa_payment(text, integer, text, numeric, text, text, text, text, jsonb) to service_role;

revoke all on public.checkout_attempts, public.mpesa_callback_events,
  public.newsletter_subscribers, public.support_requests from anon, authenticated;
grant all on public.checkout_attempts, public.mpesa_callback_events,
  public.newsletter_subscribers, public.support_requests to service_role;
grant usage, select on sequence public.checkout_attempts_id_seq to service_role;
